const budget = [
    {
      id: 1,
      date: "April 1",
      name: "Income",
      from: "Old Glory Insurance",
      amount: 1000,
      tags: ["income", "yay"],
    },
    {
      id: 2,
      date: "April 1",
      name: "Taxes",
      from: "Government",
      amount: -300,
      tags: ["taxes"],
    },
    {
      id: 3,
      date: "April 1",
      name: "Retirement",
      from: "Country Bank",
      amount: -200,
      tags: ["retirement", "investing in the future"],
    },
    {
      id: 4,
      date: "April 1",
      name: "Savings",
      from: "Country Bank",
      amount: -100,
      tags: ["savings", "rainy day fund"],
    },
    {
      id: 5,
      date: "April 1",
      name: "Credit Card Payment",
      from: "NPM Express",
      amount: -100,
      tags: ["credit card"],
    },
    {
      id: 6,
      date: "April 5",
      name: "Monthy Birthday Money from Aunt Tilda",
      from: "Aunt Tilda",
      amount: 20,
      tags: ["Aunt Tilda is the best"],
    },
    {
      id:7,
      date: "April 5",
      name: "Coffee",
      from: "Moon Coin",
      amount: -4,
      tags: ["coffee"],
    },
    {
      id: 8,
      date: "April 5",
      name: "Internet",
      from: "Horizon",
      amount: -100,
      tags: ["utilities"],
    },
    {
      id: 9,
      date: "April 3",
      name: "Groceries",
      from: "Merchant Jack's",
      amount: -76,
      tags: ["groceries"],
    },
    {
      id: 10,
      date: "April 3",
      name: "Pet Food",
      from: "Pet Precious Inc",
      amount: -7,
      tags: ["pets"],
    },
  ];
  module.exports = budget;
  